In [1]:
%load_ext autoreload

In [23]:
import numpy as np

a = np.zeros([1,1,3])
a[0,0,:] = [1,2,3]
print(a)
a[0,0] = [1,2,3]
print(a)

[[[1. 2. 3.]]]
[[[1. 2. 3.]]]


In [14]:
%autoreload 2
%cd /workspace/CornerNet-Lite
from core.config import SystemConfig
from core.dbs.coco import COCO
from core.sample.cornernet_ext import cornernet

with open(os.path.join("./configs/CornerNet_Squeeze.json"), "r") as f:
    config = json.load(f)
sys_config = SystemConfig().update_config(config["system"])

db = COCO(config["db"], "trainval", sys_config)
db.db_inds


# b = cornernet(sys_config, db, 0, None, True)

/workspace/CornerNet-Lite
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!


In [22]:
from core.models.CornerNet_Squeeze_plus import model

m = model()
m(b[0]["xs"][0])
# b[0]["xs"][0].shape

[[tensor([[[[-2.2780, -2.3046, -2.3334,  ..., -2.3386, -2.3915, -2.3805],
            [-2.4212, -2.3594, -2.4766,  ..., -2.4066, -2.3357, -2.3505],
            [-2.2595, -2.4125, -2.4509,  ..., -2.3744, -2.3353, -2.3667],
            ...,
            [-2.3729, -2.1681, -2.3828,  ..., -2.4197, -2.4421, -2.3801],
            [-2.3491, -2.3851, -2.3160,  ..., -2.3521, -2.3990, -2.3539],
            [-2.3190, -2.1998, -2.3290,  ..., -2.2055, -2.2845, -2.2983]],
  
           [[-2.2248, -2.2966, -2.3222,  ..., -2.4131, -2.2988, -2.3959],
            [-2.2891, -2.2629, -2.4030,  ..., -2.4186, -2.4257, -2.2972],
            [-2.3349, -2.1995, -2.2701,  ..., -2.3576, -2.3658, -2.2833],
            ...,
            [-2.3492, -2.1822, -2.3025,  ..., -2.3442, -2.2653, -2.2434],
            [-2.2142, -2.1458, -2.1500,  ..., -2.3060, -2.2612, -2.1656],
            [-2.2886, -2.2979, -2.4169,  ..., -2.3628, -2.3587, -2.2824]],
  
           [[-2.1302, -2.0718, -2.1891,  ..., -2.0839, -2.2014, -1.993

In [2]:
%autoreload 2
%cd /workspace/CornerNet-Lite
import os
import json
from core.dbs.coco import COCO
from core.config import SystemConfig

with open(os.path.join("./configs/CornerNet_Squeeze.json"), "r") as f:
    config = json.load(f)
sys_config = SystemConfig().update_config(config["system"])

db = COCO(config["db"], "trainval", sys_config)
db.db_inds

i = 0
db.image_path(i)
db.detections(i)
# coco.image_path(0)

/workspace/CornerNet-Lite
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!


array([[  0.,   0., 511., 511.,   5.],
       [ 67., 487., 186., 496.,   6.],
       [  0., 480., 174., 492.,   6.],
       [ 89., 426., 290., 440.,   6.],
       [124.,  64., 299., 214.,  10.],
       [124., 214., 299., 465.,  10.],
       [124., 465., 299., 511.,  10.]], dtype=float32)